version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: veridity-postgres
    environment:
      POSTGRES_DB: veridity
      POSTGRES_USER: veridity
      POSTGRES_PASSWORD: veridity123
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./configs/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U veridity"]
      interval: 5s
      timeout: 5s
      retries: 5

  n8n:
    image: n8nio/n8n:latest
    container_name: veridity-n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=veridity
      - DB_POSTGRESDB_USER=veridity
      - DB_POSTGRESDB_PASSWORD=veridity123
      - N8N_ENCRYPTION_KEY=veridity-poc-secret-key-2024
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678
      - GENERIC_TIMEZONE=UTC
    volumes:
      - n8n_data:/home/node/.n8n
      - ../n8n-workflows:/workflows:ro
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5678/healthz || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  nocodb:
    image: nocodb/nocodb:latest
    container_name: veridity-nocodb
    ports:
      - "8080:8080"
    environment:
      - NC_DB=pg://postgres:5432?u=veridity&p=veridity123&d=veridity
      - NC_AUTH_JWT_SECRET=veridity-jwt-secret-2024
      - NC_PUBLIC_URL=http://localhost:8080
      - NC_DISABLE_TELE=true
    volumes:
      - nocodb_data:/usr/app/data
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/v1/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3

  fraud-detection-api:
    image: python:3.9-slim
    container_name: veridity-fraud-api
    working_dir: /app
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    volumes:
      - ../scripts/fraud-detection:/app
    command: python -c "
      import subprocess, sys, time;
      subprocess.run([sys.executable, '-m', 'pip', 'install', 'flask', 'flask-cors', 'nltk', 'textstat', 'numpy']);
      time.sleep(2);
      exec(open('fraud_api.py').read())
    "
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import requests; requests.get(\"http://localhost:5000/health\")' || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3

volumes:
  postgres_data:
  n8n_data:
  nocodb_data:
